language: clojure
lein: lein2
script: LEIN_CMD=lein2 lein2 with-profile +travis modules do test :travis, install
branches:
  only:
    - master
jdk:
  - openjdk7
  - oraclejdk7
notifications:
  email:
    - pedestal@thinkrelevance.com
